version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cypress/base:8
        environment:
          TERM: xterm

    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-packages-v2-{{ checksum "yarn.lock" }}
            - v2-deps-{{ .Branch }}
            - v2-deps

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-v2-{{ checksum "yarn.lock" }}
          paths:
            - ~/.npm
            - ~/.cache

      #   - run:
      #       name: Build app
      #       command: yarn build

      #   - run:
      #       name: Unit tests
      #       command: yarn test

      #   - run:
      #       name: Start background app
      #       command: yarn start
      #       background: true

      #   - run:
      #       name: Cypress tests
      #       command: yarn run cypress:run

      - run: echo $CIRCLE_PULL_REQUEST | awk -F/ '{print $NF}'
